name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v5
      with:
        node-version: 24.1.0
    - name: Run tests with logs (for debugging)
      continue-on-error: true
      run: |
        cd Lab3
        echo "========== Running tests with detailed logs =========="
        node --test --experimental-test-coverage
        echo "======================================================"
    - name: Testcase 0
      id: testcase-0
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Testcase 0
        setup-command: ''
        command: cd Lab3 && ./validate.sh
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTCASE-0_RESULTS: "${{steps.testcase-0.outputs.result}}"
      with:
        runners: testcase-0
